name: Update Random Useless Fact

on:
  schedule:
    - cron: '* * * * *'  # Run every minute
  push:
    branches:
      - main

jobs:
  update_fact:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch Random Fact
      run: |
        fact=$(curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en" -H "Accept: application/json" | jq -r '.text')
        echo "Random fact of the hour: $fact" > fact.txt

    - name: Update README with the new fact
      run: |
        fact=$(cat fact.txt)
        sed -i "s|<!-- START FACT -->.*<!-- END FACT -->|<!-- START FACT -->$fact<!-- END FACT -->|" README.md

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add README.md
        git commit -m "Update random fact"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
